cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.get_cart, name="cart"),
    path("add_cart/<int:product_id>", views.add_cart, name="add_cart"),
    path("remove_cart/<int:product_id>", views.remove_cart, name="remove_cart"),
    path(
        "remove_cart_item/<int:product_id>",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path("update_cart/", views.update_cart, name="update_cart"),
    path("empty_cart/", views.empty_cart, name="empty_cart"),
]

greatkart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from store import views
from django.contrib.auth import views as auth_views

from django.contrib.sitemaps.views import sitemap

from store.sitemaps import ProductSitemap

sitemaps = {
    "products": ProductSitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("reload/", include("django_browser_reload.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("cart/", include("cart.urls")),
    path("category/", include("category.urls")),
    path("order/", include("order.urls")),
    path("store/", include("store.urls")),
    path(
        "sitemap.xml/",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = "order"

urlpatterns = [
    path("checkout/", views.checkout_order, name="checkout_order"),
    path("place_order/", views.place_order, name="place_order"),
    # path("order_complete/", views.order_complete, name="order_complete"),
    # path("payment/", views.payment, name="payment"),
    # path("order_history/", views.order_history, name="order_history"),
]

cart/models.py
from django.db import models
from store.models import Variation
from django.contrib.auth import get_user_model

from store.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=100, blank=True, editable=False)
    date_added = models.DateTimeField(auto_now_add=True)

    owner = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, editable=False, null=True, blank=True)

    def __str__(self) -> str:
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart_items')
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.quantity * self.product.price

    def add_quantity(self):
        self.quantity += 1

    def reduce_quantity(self):
        self.quantity -= 1

    def __str__(self) -> str:
        return self.product.product_name

store/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from category.models import Category


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True, blank=False)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.FloatField()
    product_image = models.ImageField(
        upload_to="photos/products/", default="defaults/default_product.jpg", blank=True)
    stock = models.IntegerField(default=0)
    is_available = models.BooleanField(default=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    date_added = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse("product_detail", args=[self.category.slug, self.slug])

    def get_absolute_url(self):
        return self.get_url()

    class Meta:
        ordering = ('-date_added',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.product_name


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(
            variation_category="color", is_active=True
        )

    def sizes(self):
        return super(VariationManager, self).filter(
            variation_category="size", is_active=True
        )


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(
        max_length=100,
        choices=(
            ("color", "color"),
            ("size", "size"),
        ),
    )
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

cart/views.py
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from cart.models import Cart, CartItem
from store.models import Product, Variation
from django.contrib import messages


def get_cart_id(request: HttpRequest):
    # try:
    #     cart_id = request.session["cart_id"]
    # except KeyError:
    #     if request.user.is_authenticated:
    #         cart, _ = Cart.objects.get_or_create(user=request.user)
    #         cart_id = cart.id
    #     else:
    # cart_id = request.session.session_key
    # if not cart_id:
    #     cart_id = request.session.create()
    return request.session.get("cart_id")


@login_required
def add_cart(request: HttpRequest, product_id):
    """Add product to cart"""
# def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    product_variations = []
    if request.method == "POST":
        for key in request.POST:
            value = request.POST[key]
            try:
                variation = Variation.objects.get(
                    product=product,
                    variation_category__iexact=key,
                    variation_value__iexact=value,
                )
                product_variations.append(variation)
            except Exception as e:
                for arg in e.args:
                    print(f"{arg}")
    stock = product.stock
    check_stock = False
    try:
        cart = Cart.objects.get(cart_id=get_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=get_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product, quantity=1, cart=cart)
        cart_item.save()

    if stock >= cart_item.quantity:
        check_stock = True
        return redirect("cart:cart")
    # if check_stock:
    else:
        messages.error(
            request,
            f"Only {stock} items available in stock.",
            extra_tags="danger",
        )
        quantity = cart_item.quantity
        context = {
            "check_stock": check_stock,
            "stock": stock,
            "quantity": quantity,
            "product": Product,
        }
        return render(request, "cart/stock_warning.html", context)


@login_required
def remove_cart(request, product_id):
    cart = Cart.objects.get(cart_id=get_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect("cart:cart")


def remove_cart_item(request, product_id):
    cart = Cart.objects.get(cart_id=get_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect("cart:cart")


@login_required
def get_cart(request: HttpRequest):
    total = 0
    quantity = 0
    cart_items = []
    items_count = 0
    tax = 0
    grand_total = 0
    context = {}
    try:
        cart = Cart.objects.get(cart_id=get_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        items_count = cart_items.count()
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except Exception as e:
        print(f"{e.args}")
    context = {
        "total": total,
        "tax": tax,
        "grand_total": grand_total,
        "cart_items": cart_items,
        "quantity": quantity,
        "items_count": items_count,
    }
    return render(request, "cart/cart.html", context)


@login_required
def update_cart(request):
    if request.method == "POST":
        print(f"\n\n{request.POST}\n\n")
        data = request.POST.copy()
        data.pop("csrfmiddlewaretoken")
        for k, v in data.items():
            print(f"{k} : {v}")
            if k.startswith("quantity_"):
                cart_item_id = k.split("_")[1]
                new_quantity = int(v)
                update_cart_item_quantity(request, cart_item_id, new_quantity)
        return redirect("cart:cart")
    else:
        messages.error(request, "Invalid request method", extra_tags="danger")
    return redirect("cart:cart")


def update_cart_item_quantity(request, cart_item_id, new_quantity):
    cart_item = CartItem.objects.get(id=cart_item_id)
    old_quantity = cart_item.quantity
    if new_quantity <= cart_item.product.stock:
        cart_item.quantity = new_quantity
        print(f"===>{new_quantity=}<===")
        cart_item.save()
        messages.success(
            request,
            f"Updated {cart_item.product.product_name} quantity to {new_quantity}",
            extra_tags="success",
        )
    else:
        if old_quantity <= cart_item.product.stock:
            cart_item.quantity = old_quantity
            print(f"===>{old_quantity=}<===")
        else:
            cart_item.quantity = cart_item.product.stock
        cart_item.save()
        messages.error(
            request,
            f"Cannot update {cart_item.product.product_name} quantity to {new_quantity}. Only {cart_item.product.stock} available.",
            extra_tags="danger",
        )


@login_required
def empty_cart(request):
    """Empty the cart"""
    try:
        cart = Cart.objects.get(cart_id=get_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart)
        cart_items.delete()
        messages.success(request, "Cart emptied successfully",
                         extra_tags="success")
    except Cart.DoesNotExist:
        messages.error(request, "Cart does not exist", extra_tags="danger")
    return redirect("cart:cart")

templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<section class="section-content padding-y bg">
	<div class="container">

		<!-- ============================ COMPONENT 1 ================================= -->
		{% if items_count %}
		<div class="row justify-content-center">
			<aside class="col-lg-9">
				<div class="card">
					<form method="POST" action="{% url 'cart:update_cart' %}">
						{% csrf_token %}
						<table class="table table-borderless table-shopping-cart">
							<thead class="text-muted">
								<tr class="small text-uppercase">
									<th scope="col">Product</th>
									<th scope="col" width="120">Quantity</th>
									<th scope="col" width="120">Price</th>
									<th scope="col" class="text-right" width="200"> </th>
								</tr>
							</thead>
							<tbody>

								{% for ci in cart_items %}
								<tr>
									<td class="">
										<figure class="itemside align-items-center">
											<div class="aside">
												<a href="{{ci.product.product_image.url}}">
													<img src="{{ci.product.product_image.url}}" class="img-sm">
												</a>
											</div>
											<figcaption class="info">
												<a href="{{ci.product.get_url}}"
													class="title {% if ci.quantity > ci.product.stock %}text-warning{% endif %}">{{ci.product.product_name}}</a>
												{% for color in ci.product.variation_set.colors %}
												<p class="text-muted small">Color: {{color.variation_value}}</p>
												{% endfor %}
												{% for size in ci.product.variation_set.sizes %}
												<p class="text-muted small">Size: {{size.variation_value}}</p>
												{% endfor %}
											</figcaption>
										</figure>
									</td>
									<td>
										<!-- col.// -->
										<div class="col">
											<div class="input-group input-spinner">
												<div class="input-group-prepend">
													<a href="{% url 'cart:remove_cart' ci.product.id %}"
														class="btn btn-light" type="button" id="button-plus"> <i
															class="fa fa-minus"></i> </a>
												</div>
												<input type="text" class="form-control" name="quantity_{{ci.id}}" value="{{ci.quantity}}" di>
												<div class="input-group-append">
													<a href="{% url 'cart:add_cart' ci.product.id %}" class="btn btn-light"
														type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
												</div>
											</div> <!-- input-group.// -->
										</div> <!-- col.// -->
									</td>
									<td>
										<div class="price-wrap">
											<var class="price">$ {{ci.sub_total | intcomma}}</var>
											<small class="text-muted"> $ {{ci.product.price | intcomma}} each </small>
										</div> <!-- price-wrap .// -->
									</td>
									<td class="text-right">
										<a href="{% url 'cart:remove_cart_item' ci.product.id %}" class="btn btn-outline-danger btn-sm">
											Remove</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
							<tfoot>
								<tr class="py-5">
									<td></td>
									<td>
										<a href='{% url "cart:empty_cart" %}' class="btn btn-outline-danger">Clear</a>
									</td>
									<td>
										<button class="btn btn-outline-info" type="submit">
											Update
										</button>
									</td>
								</tr>
							</tfoot>
						</table>
					</form>
				</div> <!-- card.// -->

			</aside> <!-- col.// -->
			<aside class="col-lg-3">

				<div class="card">
					<div class="card-body">
						<dl class="dlist-align">
							<dt>Total price:</dt>
							<dd class="text-right">$ {{total | intcomma}} </dd>
						</dl>
						<dl class="dlist-align">
							<dt>Tax:</dt>
							<dd class="text-right"> $ {{tax | intcomma}}</dd>
						</dl>
						<dl class="dlist-align">
							<dt>Grand Total:</dt>
							<dd class="text-right text-dark b"><strong>$ {{grand_total | intcomma}}</strong></dd>
						</dl>
						<hr>
						<p class="text-center mb-3">
							<img src="{% static './images/misc/payments.png' %}" height="26">
						</p>
						<a href="{% url 'order:place_order' %}" class="btn btn-primary btn-block"> Checkout </a>
						<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
					</div> <!-- card-body.// -->
				</div> <!-- card.// -->

			</aside> <!-- col.// -->

		</div> <!-- row.// -->
		{% else %}
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-8 alert alert-warning" role="alert">
					<h5 class="text-center">Your Cart is Empty !</h5>
				</div>
			</div>
			<div class="row justify-content-center">
				<a name="" id="" class="btn btn-outline-primary" href=" {% url 'store' %} " role="button">
					Continue Shopping
				</a>
			</div>
		</div>
		{% endif %}
		<!-- ============================ COMPONENT 1 END .// ================================= -->

	</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/cart/stock_warning.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-8 alert alert-warning" role="alert">
                <p class="text-center">The item quantity is bigger than the stock available, <br>
                Please make sure you do not go beyond the stock available !
                </p>
            </div>
            <div class="alert alert-info" role="alert">
                <p class="text-center">
                    The concerned products have their titles colored with orange !
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <a name="" id="" class="btn btn-outline-primary" href=" {% url 'cart:cart' %} " role="button">
                Check Your Cart
            </a>
        </div>
    </div>
{% endblock content %}