accounts/urls.py
from . import views
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views

app_name = "accounts"


urlpatterns = [
    # path("login/", LoginView.as_view(template_name="accounts/login.html"), name="login"),

    # path("login/", views.UserLoginView.as_view(), name="login"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path('update/<int:pk>/', views.update_user, name='update_user'),

]
password_reset_views = [
    path("password_reset/", auth_views.PasswordResetView.as_view(
        template_name="accounts/password_reset.html", email_template_name="accounts/password_reset_email.html",
        success_url=reverse_lazy("accounts:password_reset_done"), extra_email_context={
            'domain': 'localhost:8000',  # Use localhost for development
            'protocol': 'http',  # Use http for local development
        }), name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html",
        success_url=reverse_lazy("accounts:password_reset_complete")), name="password_reset_confirm"),
    path("reset_done/", auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),]


password_change_views = [
    path("password_change/", views.CustomPasswordChangeView.as_view(), name="password_change"),
    path("password_change_done/", auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_change_done.html"), name="password_change_done"),
]

profile_views = [
    path("profile/", views.user_profile_view, name="profile"),
    path("delete/", views.delete_account, name="delete_account"),
]

urlpatterns += password_reset_views + password_change_views + profile_views

cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.get_cart, name="cart"),
    path("add_cart/<int:product_id>", views.add_cart, name="add_cart"),
    path("remove_cart/<int:product_id>", views.remove_cart, name="remove_cart"),
    path(
        "remove_cart_item/<int:product_id>",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path("update_cart/", views.update_cart, name="update_cart"),
    path("empty_cart/", views.empty_cart, name="empty_cart"),
]

greatkart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from store import views
from django.contrib.auth import views as auth_views

from django.contrib.sitemaps.views import sitemap

from store.sitemaps import ProductSitemap

sitemaps = {
    "products": ProductSitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("reload/", include("django_browser_reload.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("cart/", include("cart.urls")),
    path("category/", include("category.urls")),
    path("order/", include("order.urls")),
    path("store/", include("store.urls")),
    path(
        "sitemap.xml/",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.safestring import mark_safe

from .models import UserProfile, CustomUser


class UserLoginForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'password']
        widgets = {
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'}),
        }


class UserSignUpForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError('Passwords do not match')
        return cleaned_data


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'bio', 'title', 'first_name', 'last_name',
                  'phone_number', 'address', 'city', 'state', 'country', 'zip_code']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Replace the 'user' field with a hyperlink
        if self.instance and self.instance.user:
            user_update_url = reverse('accounts:update_user', kwargs={
                                      'pk': self.instance.user.pk})
            self.fields['user'] = forms.CharField(
                label='User',
                required=False,
                widget=forms.TextInput(attrs={
                    'readonly': 'readonly',
                    'value': f'{self.instance.user.username}',
                })
            )
            # Add the hyperlink to the field's help text
            self.fields['user'].help_text = mark_safe(
                f'<a href="{user_update_url}">Click here to update user details</a>')

    def save(self, user, *args, **kwargs):
        profile = super().save(commit=False)
        profile.user = user  # Set the user to the currently logged-in user
        if kwargs.get('commit', True):
            profile.save()
        return profile


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']

accounts/views.py
import re
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import (PasswordChangeView,
                                       PasswordResetConfirmView)
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View

from .forms import (UserLoginForm, UserProfileForm, UserSignUpForm,
                    UserUpdateForm)


class UserRegisterView(View):

    def get(self, request: HttpRequest):
        return render(request, 'accounts/register.html')

    def post(self, request: HttpRequest):
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            user_model = get_user_model()
            user_model.objects.create_user(
                username=form.cleaned_data.get('username'),
                email=form.cleaned_data.get('email'),
                password=form.cleaned_data.get('password'),
            )
            messages.success(request,
                             'Account created successfully',
                             extra_tags='success')
            return redirect('accounts:login')
        else:
            context = {'form': form}
            messages.error(request,
                           'Invalid form submission',
                           extra_tags='danger')
            print(form.errors)
            return render(request, 'accounts/register.html', context=context)


class UserLoginView(UserPassesTestMixin, View):

    def test_func(self):
        # Allow access only if the user is not authenticated
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        # Redirect authenticated users to the home page (or another page)
        return redirect('home')

    def get(self, request: HttpRequest):
        form = UserLoginForm()
        context = {'form': form}
        # Render the login page for GET requests
        return render(request, 'accounts/login.html', context=context)

    def post(self, request: HttpRequest):
        # Handle login logic for POST requests
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)
            if user:
                auth_login(request, user)
                next_url = request.GET.get('next', 'home')
                return redirect(next_url)
            else:
                messages.error(request,
                               'Invalid login credentials',
                               extra_tags='danger')
        context = {'form': form}
        return render(request, 'accounts/login.html', context=context)


def user_is_logged_out(user: User):
    return not user.is_authenticated


@user_passes_test(user_is_logged_out,)
def user_login(request: HttpRequest):
    # if request.user.is_authenticated:
    #     # Redirect authenticated users to the previous page or fallback to 'home'
    #     previous_url = request.META.get('HTTP_REFERER', 'home')
    #     return redirect(previous_url)

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user:
            auth_login(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Login successful',
                                 extra_tags='success')

            # Redirect to the 'next' parameter if it exists, otherwise go to the home page
            # 'home' is the fallback URL name
            next_url = request.GET.get('next', "home")
            return redirect(next_url)
        else:
            messages.error(request,
                           'Invalid login credentials',
                           extra_tags='danger')
            return redirect('accounts:login')
    return render(request, 'accounts/login.html')


def user_logout(request: HttpRequest):
    if request.user.is_authenticated:
        logout(request)
        messages.add_message(request, messages.SUCCESS, message='Logout successful',
                             extra_tags='success')
    return render(request, 'accounts/logout.html')


class CustomPasswordChangeView(PasswordChangeView):
    template_name = "accounts/password_change.html"
    # Redirect to login page after logout
    success_url = reverse_lazy("accounts:password_change_done")

    def form_valid(self, form):
        # Log out the user after a successful password change
        response = super().form_valid(form)
        logout(self.request)
        messages.success(self.request, 'Password changed successfully. Please login again.',
                         extra_tags='success')
        return response


@login_required
def user_profile_view(request: HttpRequest):
    profile = request.user.profile
    print(f"{request.user.is_superuser=}")
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save(user=request.user, commit=True)
            messages.success(request,
                             'Profile updated successfully',
                             extra_tags='success')
            return redirect('accounts:profile')
        else:
            messages.error(
                request, 'Please correct the errors below.', extra_tags="danger")
            return render(request, 'accounts/profile.html', {'form': form})
    else:
        form = UserProfileForm(instance=profile)
    return render(request, 'accounts/profile.html', {'form': form})


@login_required
def delete_account(request: HttpRequest):
    if request.user.is_authenticated:
        user = request.user
        user.delete()
        messages.success(request,
                         'Account deleted successfully',
                         extra_tags='success')
        return redirect('home')


@login_required
def update_user(request: HttpRequest, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'User details updated successfully.', extra_tags="success")
            return redirect('accounts:profile')  # Redirect to the profile page
        else:
            messages.error(
                request, 'Please correct the errors below.', extra_tags="danger")
            return render(request, 'accounts/update_user.html', {'form': form})
    else:
        form = UserUpdateForm(instance=user)
    return render(request, 'accounts/update_user.html', {'form': form})

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
    Login
{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
      <form method='POST' action="{% url 'accounts:login' %}?next={{ request.GET.next | default:'/home' }}">
          {% csrf_token %}
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email" required>
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name="password" required>
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href='{% url "accounts:password_reset" %}' class="float-right">Forgot password?</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="#">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/logout.html
{% extends "base.html" %} 

{% block title %} Logout {% endblock title %} 

{% block content %}
<div class="container mt-5">
    <div class="d-flex flex-column align-items-center">
        <p class="text-center my-5">
            You can  
            <a href="{% url 'accounts:login' %}" class="btn btn-outline-info">Login again ...</a>
        </p>
        <p class="text-center">
            Or  <a href='{% url "home" %}' class="btn btn-outline-primary">Browse Products</a>
        </p>
    </div>
</div>

{% endblock content %}

templates/accounts/password_change.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            <h2 class="py-5">Change Password</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary">Change Password</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

templates/accounts/password_change_done.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            <h2 class="py-5">Password Changed</h2>
            <p>Your password has been successfully changed.</p>
            <a href="{% url 'accounts:login' %}" class="btn btn-primary">Log In</a>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

templates/accounts/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            <h2>Password Reset</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="row justify-content-center mt-3">
                    <button type="submit" class="btn btn-primary">Reset Password</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col"></div>
        <div class="col">
            <h2 class="py-5">Password Reset Complete</h2>
            <p>Your password has been successfully reset. You can now <a href="{% url 'accounts:login' %}">log in</a>.</p>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col"></div>
        <div class="col d-block">
            <h2 class="py-5">Set New Password</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary">Set Password</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col py-5"></div>
        <div class="col">
            <h2 class="py-5">Password Reset Sent</h2>
            <p>An email has been sent to the provided address with instructions to reset your password.</p>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

templates/accounts/password_reset_email.html
{% load i18n %}

{% blocktrans %}You're receiving this email because you requested a password reset for your user account at
http://localhost:8000 .{% endblocktrans %}
{% blocktrans %}Please go to the following page and choose a new password:{% endblocktrans %}

<a href="http://localhost:8000/{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">
    http://localhost:8000/{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
</a>

{% blocktrans %}Your username, in case you’ve forgotten: {{ user.get_username }}{% endblocktrans %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}User Profile{% endblock %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col"></div>
      <div class="col">
        <h2 class="py-5">Profile Update</h2>
        {% if user.profile.profile_picture %}
        <a href='{{user.profile.profile_picture.url}}' class="" >
          <img class="img-thubnail rounded-circle" src='{{user.profile.thumbnail.url}}' alt="profile_picture" srcset="" width="200px" height="200px">
        </a>
        {% else %}
          <img class="img-thumbnail rounded-circle" src='/media/defaults/default_user.jpg' alt="profile_picture" srcset="" width="200px" height="200px">
        {% endif %}
      </div>
      <div class="col"></div>
    </div>
    <hr>
    <div class="row justify-content-center py-5">
      <div class="col">
      </div>
      <div class="col-6">
        <form method="POST" action="{% url 'accounts:profile' %}" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy}}
          <div class="row justify-content-center py-3">
            <button type="submit" class="btn btn-outline-primary">Update Profile</button>
          </div>
        </form>
      </div>
      <div class="col"></div>
    </div>
    <hr>
    {% if request.user.is_superuser %}
    <div class="row justify-content-center">
      <div class="col"></div>
        <div class="col-6 d-block">
          <h4 class="text-center">Account Deletion</h4>
          <div class="text-center">
            <form method="POST" action="{% url 'accounts:delete_account' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-danger">Delete Account?</button>
            </form>
          </div>
        </div>
        <div class="col"></div>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% block title %}
    Register
{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
        <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
        <form method='POST' action="{% url 'accounts:register' %}">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for field, error in form.errors.items %}
                        {{field}}: {{error}}
                    {% endfor %}
                </div>
            {% endif %}
            {% for field in form.fields %}
                <p>
                    <label>{{field.label}}</label>
                    {{field}}
                </p>
            {% endfor %}
            <div class="form-group">
                <label>Username</label>
                <input type="text" class="form-control" placeholder="" name="username">
            </div>
            <div class="form-group">
                <label>Email</label>
                <input type="email" class="form-control" placeholder="" name="email">
                <small class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div> <!-- form-group end.// -->
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label>Create password</label>
                    <input class="form-control" type="password" name="password">
                </div> <!-- form-group end.// --> 
                <div class="form-group col-md-6">
                    <label>Repeat password</label>
                    <input class="form-control" type="password" name="confirm_password">
                </div> <!-- form-group end.// -->  
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Register  </button>
            </div> <!-- form-group// -->      
                
        </form>
       </article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="">Log In</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/update_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}
    User Update
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col"></div>
        <div class="col-6">
            <h2 class="py-5">Profile Update</h2>
            {% if user.profile.profile_picture %}
            <a href='{{user.profile.profile_picture.url}}' class="" >
                <img class="img-thubnail rounded-circle" src='{{user.profile.thumbnail.url}}' alt="profile_picture" srcset="" width="200px" height="200px">
            </a>
            {% else %}
                <img class="img-thubnail rounded-circle" src='/media/defaults/default_user.jpg' alt="profile_picture" srcset="" width="200px" height="200px">
            {% endif %}
            <form method="post">
                {% csrf_token %}
                {{ form|crispy}}
                <div class="row justify-content-center py-3">
                    <button type="submit" class="btn btn-outline-primary">Update Profile</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}