accounts/urls.py
from . import views
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views

app_name = "accounts"


urlpatterns = [
    # path("login/", LoginView.as_view(template_name="accounts/login.html"), name="login"),

    # path("login/", views.UserLoginView.as_view(), name="login"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path('update/<int:pk>/', views.update_user, name='update_user'),

]
password_reset_views = [
    path("password_reset/", auth_views.PasswordResetView.as_view(
        template_name="accounts/password_reset.html", email_template_name="accounts/password_reset_email.html",
        success_url=reverse_lazy("accounts:password_reset_done"), extra_email_context={
            'domain': 'localhost:8000',  # Use localhost for development
            'protocol': 'http',  # Use http for local development
        }), name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html",
        success_url=reverse_lazy("accounts:password_reset_complete")), name="password_reset_confirm"),
    path("reset_done/", auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),]


password_change_views = [
    path("password_change/", views.CustomPasswordChangeView.as_view(), name="password_change"),
    path("password_change_done/", auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_change_done.html"), name="password_change_done"),
]

profile_views = [
    path("profile/", views.user_profile_view, name="profile"),
    path("delete/", views.delete_account, name="delete_account"),
]

urlpatterns += password_reset_views + password_change_views + profile_views

cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.get_cart, name="cart"),
    path("add_cart/<int:product_id>", views.add_cart, name="add_cart"),
    path("remove_cart/<int:product_id>", views.remove_cart, name="remove_cart"),
    path(
        "remove_cart_item/<int:product_id>",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path("update_cart/", views.update_cart, name="update_cart"),
    path("empty_cart/", views.empty_cart, name="empty_cart"),
]

greatkart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from store import views
from django.contrib.auth import views as auth_views

from django.contrib.sitemaps.views import sitemap

from store.sitemaps import ProductSitemap

sitemaps = {
    "products": ProductSitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("reload/", include("django_browser_reload.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("cart/", include("cart.urls")),
    path("category/", include("category.urls")),
    path("order/", include("order.urls")),
    path("store/", include("store.urls")),
    path(
        "sitemap.xml/",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top" id="my-footer">
    <div class="container">
    <section class="footer-bottom border-top row justify-content-between">
        <div class="col-md-2">
        <p class="text-muted"> &copy {% now "Y" %} Company name </p>
        </div>
        <div class="col-md-8 text-md-center">
        Email:<span class="text-muted px-2">jonasinfo2016@gmail.com</span>
        Phone:<span class="text-muted px-2">+237 683359297</span>
        </div>
        <div class="col-md-2 text-md-right text-muted">
        <strong class="fab fa-lg fa-cc-visa"></strong>
        <strong class="fab fa-lg fa-cc-paypal"></strong>
        <strong class="fab fa-lg fa-cc-mastercard"></strong>
        </div>
    </section>
    </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

templates/includes/navbar.html
{% load static %}

<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> Language </a>
                <ul class="dropdown-menu small">
                    <li><a class="dropdown-item" href="#">English</a></li>
                    <li><a class="dropdown-item" href="#">French</a></li>
                    <li><a class="dropdown-item" href="#">Arabic</a></li>
                    <li><a class="dropdown-item" href="#">Russian </a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> USD </a>
                <ul class="dropdown-menu small">
                    <li><a class="dropdown-item" href="#">EUR</a></li>
                    <li><a class="dropdown-item" href="#">AED</a></li>
                    <li><a class="dropdown-item" href="#">RUBL </a></li>
                    <li><a class="dropdown-item" href="#">XAF </a></li>
                </ul>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="#" class="nav-link"> <em class="fa fa-envelope"></em> Email </a></li>
            <li><a href="#" class="nav-link"> <em class="fa fa-phone"></em> Call us </a></li>
            <li><a href="#" class="nav-link"> <em class="fa fa-phone"></em> {{name}} </a></li>
        </ul> <!-- list-inline //  -->
        </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
    </nav>

    <section class="header-main border-bottom">
    <div class="container-fluid px-md-5">
        <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="{% url 'home' %}" class="brand-wrap">
                <img class="logo" src={% static 'images/logo.png' %} alt='logo'>
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                <strong class="fa fa-bars"></strong> All category
            </button>
            <div class="dropdown-menu">
                    <a class='dropdown-item' href="{% url 'store' %}">All products</a>
                {% for c in categories %}
                    <a class="dropdown-item" href="{{c.get_url}}">{{c.category_name}}</a>
                {% endfor %}
            </div>
            </div> <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <a href={% url 'store' %} class="btn btn-outline-primary">Store</a>
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form method='GET' action="{% url 'search' %}" class="search">
            <div class="input-group w-100">
                <input type="text" class="form-control" style="width:60%;" placeholder="Search ..." name="keyword">

                <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <strong class="fa fa-search"></strong>
                </button>
                </div>
            </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
            <div class="d-flex justify-content-end mb-3 mb-lg-0">
                <a href="{% url 'cart:cart' %}" class="widget-header">
                    <div class="icon icon-sm rounded-circle border "><strong class="fa fa-shopping-cart"></strong></div>
                    <span class="badge badge-pill badge-danger notify"> {{cart_items_count}} </span>
                </a>
                <div class="widget-header px-5">
                    {% if user.is_authenticated %}
                        <a href="#" class="dropdown-toggle text-muted" data-toggle="dropdown">
                            {{display_name}}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href='{% url "accounts:profile" %}'>
                                Profile<i class="fas fa-user-alt pl-3"></i>
                            </a></li>
                            <li class="">
                                <a class="dropdown-item" href='{% url "accounts:logout" %}'> 
                                    Logout
                                    <i class="fas fa-sign-out-alt pl-3"></i>
                                </a>
                            </li>
                        </ul>
                    {% else %}
                        <small class="title text-muted">{{display_name}}</small>
                        <a href='{% url "accounts:login" %}'>
                        <i class="fas fa-sign-in-alt"></i> Sign in
                        </a> <span class="dark-transp"> | </span>
                        <a href='{% url "accounts:register" %}'>
                            <i class="fas fa-user-plus"></i> Register</a> 
                    {% endif %}
                    <div>
                </div>
            </div>
            </div> <!-- widgets-wrap.// -->
        </div> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- container.// -->
    </section> <!-- header-main .// -->
</header> <!-- section-header.// -->