cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.get_cart, name="cart"),
    path("add_cart/<int:product_id>", views.add_cart, name="add_cart"),
    path("remove_cart/<int:product_id>", views.remove_cart, name="remove_cart"),
    path(
        "remove_cart_item/<int:product_id>",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path("update_cart/", views.update_cart, name="update_cart"),
    path("empty_cart/", views.empty_cart, name="empty_cart"),
]

category/urls.py
from django.urls import path

from . import views


app_name = 'category'

urlpatterns = [
    path('', views.category_list, name='category_list'),
    path('<int:category_id>/', views.category_detail, name='category_detail'),
    path('delete/<int:category_id>/', views.category_delete, name='category_delete'),
    path('add/', views.category_create, name='category_add'),
]

greatkart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from store import views
from django.contrib.auth import views as auth_views

from django.contrib.sitemaps.views import sitemap

from store.sitemaps import ProductSitemap

sitemaps = {
    "products": ProductSitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("reload/", include("django_browser_reload.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("cart/", include("cart.urls")),
    path("category/", include("category.urls")),
    path("order/", include("order.urls")),
    path("store/", include("store.urls")),
    path(
        "sitemap.xml/",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_categories'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'),
    path('product/', views.product_list, name='product_list'),
    path('product/add/', views.product_create, name='product_create'),
    path('product/<int:id>/', views.product_update, name='product_update'),
    path('product/delete/<int:id>/', views.product_delete, name='product_delete'),
    path('search/', views.search, name='search'),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from category.models import Category


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True, blank=False)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.FloatField()
    product_image = models.ImageField(
        upload_to="photos/products/", default="defaults/default_product.jpg", blank=True)
    stock = models.IntegerField(default=0)
    is_available = models.BooleanField(default=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    date_added = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse("product_detail", args=[self.category.slug, self.slug])

    def get_absolute_url(self):
        return self.get_url()

    class Meta:
        ordering = ('-date_added',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.product_name


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(
            variation_category="color", is_active=True
        )

    def sizes(self):
        return super(VariationManager, self).filter(
            variation_category="size", is_active=True
        )


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(
        max_length=100,
        choices=(
            ("color", "color"),
            ("size", "size"),
        ),
    )
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

store/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "product_image",
            "product_name",
            "slug",
            "description",
            "price",
            "stock",
            "is_available",
            "category",
        ]
        widgets = {
            "product_name": forms.TextInput(attrs={"class": "form-control"}),
            "slug": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "price": forms.NumberInput(attrs={"class": "form-control"}),
            "product_image": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "stock": forms.NumberInput(attrs={"class": "form-control"}),
            "is_available": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "category": forms.Select(attrs={"class": "form-select"}),
        }
        labels = {
            "product_name": "Product Name",
            "slug": "Slug",
            "description": "Product Description",
            "price": "Price",
            "product_image": "Product Image",
            "stock": "Stock",
            "is_available": "Is Available",
            "category": "Product Category",
        }
        help_texts = {
            "product_name": "Enter the name of the product.",
            "slug": "Enter a unique slug for the product or leave blank to auto-generate.",
            "description": "Enter a description of the product.",
            "price": "Enter the price of the product.",
            "product_image": "Upload an image of the product.",
            "stock": "Enter the stock quantity of the product.",
            "is_available": "Check if the product is available.",
            "category": "Select a category for the product.",
        }

store/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render

from cart.models import Cart, CartItem
from cart.views import get_cart_id
from category.models import Category
from store.forms import ProductForm
from store.models import Product


def home(request: HttpRequest):
    # 10 random products
    products = Product.objects.filter(is_available=True).order_by("?")[:10]
    context = {"products": products}

    return render(request, "home.html", context=context)


def store(request, category_slug=None):
    products = ""
    category = category_slug
    if category:
        category = get_object_or_404(Category, slug=category_slug)
        products = (
            Product.objects.all()
            .filter(category=category, is_available=True)
            .order_by("-id")
        )
        paginator = Paginator(products, 1)
        page = request.GET.get("page")
        paged_products = paginator.get_page(page)
    else:
        products = Product.objects.all().filter(is_available=True).order_by("-id")
        paginator = Paginator(products, 3)
        page = request.GET.get("page")
        paged_products = paginator.get_page(page)
    context = {
        "products": paged_products,
        "total": products.count(),
        "category": category,
    }
    return render(request, "store/store.html", context)


def product_detail(request, category_slug, product_slug):
    is_cart_item = False
    p = get_object_or_404(Product, slug=product_slug)
    cart_id = get_cart_id(request)
    cart = Cart.objects.filter(cart_id=cart_id)
    cart_items = CartItem.objects.filter(cart=cart[:1])
    category_slug2 = category_slug
    for item in cart_items:
        if item.product.id == p.id:
            is_cart_item = True
    context = {
        "p": p,
        "category_slug": category_slug2,
        "is_cart_item": is_cart_item,
    }
    return render(request, "store/product_detail.html", context)


def search(request):
    kw = ""
    if "keyword" in request.GET:
        kw = request.GET["keyword"]
    # if kw != '':
    # if kw:
    products = Product.objects.all().filter(
        Q(product_name__icontains=kw) | Q(description__icontains=kw)
    )
    # paginator = Paginator(products, 10)
    # page = request.GET.get('page')
    # paged_products = paginator.get_page(page)
    context = {
        "products": products,
        "total": products.count(),
        "keyword": kw,
    }
    return render(request, "store/store.html", context)
    # else:
    #     return redirect('store')
    # else:
    #     return redirect('store')


def product_update(request: HttpRequest, id):
    product = get_object_or_404(Product, id=id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(
                request=request, message="Product updated successfully.", extra_tags="success")
            return redirect("product_list")
        else:
            messages.error(
                request=request, message="Error updating product.", extra_tags="danger")
            return render(
                request=request,
                template_name="store/product_update.html",
                context={"form": form, "product": product},
            )
    else:
        form = ProductForm(instance=product)
        if request.user.has_perm("store.add_product"):
            for field in form.fields.values():
                # field.widget.attrs["disabled"] = True
                # field.widget.attrs["readonly"] = True
                print(
                    f'{field}\n===>{field.widget.attrs}', end="<====\n")
        return render(
            request=request,
            template_name="store/product_update.html",
            context={"form": form, "product": product},
        )


def product_delete(request: HttpRequest, id):
    product = get_object_or_404(Product, id=id)
    product.delete()
    messages.success(
        request=request, message="Product deleted successfully.", extra_tags="success")
    return redirect("product_list")


def product_create(request: HttpRequest):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(
                request=request, message="Product created successfully.", extra_tags="success")
            return redirect("product_list")
        else:
            messages.error(
                request=request, message="Error creating product.", extra_tags="danger")
            return render(
                request=request,
                template_name="store/product_create.html",
                context={"form": form},
            )
    else:
        form = ProductForm()
        return render(
            request=request,
            template_name="store/product_create.html",
            context={"form": form},
        )


def product_list(request: HttpRequest):
    products = Product.objects.all()
    paginator = Paginator(products, 10)
    page = request.GET.get("page")
    paged_products = paginator.get_page(page)
    context = {
        "products": paged_products,
        "total": products.count(),
    }
    return render(request, "store/product_list.html", context)

templates/store/category_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Category - {{ category.name }}
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row py-5">
        <div class="col"></div>
        <div class="col-6">
            <form method="POST">
                {% csrf_token %}

                <!-- Render the form -->
                {{ form|crispy }}

                <div class="row justify-content-end p-3"><button type="submit"
                        class="btn btn-outline-primary">Create</button></div>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>

{% endblock content %}

templates/store/category_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Category - {{ category.name }}
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row py-5">
        <div class="col"></div>
        <div class="col-6">
            <div class="text-center py-3">
                {% if category %}
                    {% if category.category_image %}
                        <a href='{{category.category_image.url}}' class="">
                            <img class="img-thubnail rounded-circle" src='{{category.category_image.url}}' alt="profile_picture" srcset=""
                                width="200px" height="200px">
                        </a>
                    {% endif %}
                {% endif %}
            </div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- Render the form -->
                {{ form|crispy }}
    
                <div class="row justify-content-end p-3"><button type="submit" class="btn btn-outline-primary">Update</button></div>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>

{% endblock content %}

templates/store/category_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Category - {{ category.name }}
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row py-5">
        <div class="col"></div>
        <div class="col-6">
            <table class="table table-hover table-responsive table-striped table-borderless">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Slug</th>
                        <th scope="col">Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                        <tr>
                            <th scope="row">{{category.id}}</th>
                            <td>{{category.category_name}}</td>
                            <td>{{category.slug}}</td>
                            <td>
                                <a href='{% url "category:category_detail" category.id %}' class="btn-outline-info btn-sm">
                                    View...
                                </a>
                            </td>
                            <td>
                                <a href='{% url "category:category_delete" category.id %}' class="btn-outline-danger btn-sm">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col"></div>
    </div>
</div>

{% endblock content %}

templates/store/place-order.html
{% extends "base.html" %}
{% load static %}

{% block title %}
 Place Order
{% endblock title %}


{% block content %}

<section class="section-content padding-y bg">
			<div class="container">



				<!-- ============================ COMPONENT 2 ================================= -->
				<div class="row">
					<main class="col-md-8">

						<article class="card mb-4">
							<div class="card-body">
								<h4 class="card-title mb-4">Review cart</h4>
								<div class="row">
									<div class="col-md-6">
										<figure class="itemside  mb-4">
											<div class="aside"><img src='{% static "images/items/1.jpg" %}' class="border img-sm">
											</div>
											<figcaption class="info">
												<p>Apple iPad (2019) 32Gb Wi-Fi gold </p>
												<span class="text-muted">2x = $560 </span>
											</figcaption>
										</figure>
									</div> <!-- col.// -->
									<div class="col-md-6">
										<figure class="itemside  mb-4">
											<div class="aside"><img src='{% static "images/items/2.jpg" %}' class="border img-sm">
											</div>
											<figcaption class="info">
												<p>Apple iPad (2019) 32Gb Wi-Fi gold </p>
												<span class="text-muted">2x = $560 </span>
											</figcaption>
										</figure>
									</div> <!-- col.// -->
									<div class="col-md-6">
										<figure class="itemside mb-4">
											<div class="aside"><img src='{% static "images/items/3.jpg" %}' class="border img-sm">
											</div>
											<figcaption class="info">
												<p>Apple iPad (2019) 32Gb Wi-Fi gold </p>
												<span class="text-muted">2x = $560 </span>
											</figcaption>
										</figure>
									</div> <!-- col.// -->
									<div class="col-md-6">
										<figure class="itemside  mb-4">
											<div class="aside"><img src='{% static "images/items/4.jpg" %}' class="border img-sm">
											</div>
											<figcaption class="info">
												<p>Apple iPad (2019) 32Gb Wi-Fi gold </p>
												<span class="text-muted">2x = $560 </span>
											</figcaption>
										</figure>
									</div> <!-- col.// -->
								</div> <!-- row.// -->
							</div> <!-- card-body.// -->
						</article> <!-- card.// -->


						<article class="card mb-4">
							<div class="card-body">
								<h4 class="card-title mb-4">Contact info</h4>
								<form action="">
									<div class="row">
										<div class="form-group col-sm-6">
											<label>Frst name</label>
											<input type="text" placeholder="Type here" class="form-control">
										</div>
										<div class="form-group col-sm-6">
											<label>Last name</label>
											<input type="text" placeholder="Type here" class="form-control">
										</div>
										<div class="form-group col-sm-6">
											<label>Phone</label>
											<input type="text" value="+998" class="form-control">
										</div>
										<div class="form-group col-sm-6">
											<label>Email</label>
											<input type="email" placeholder="example@gmail.com" class="form-control">
										</div>
									</div> <!-- row.// -->
								</form>
							</div> <!-- card-body.// -->
						</article> <!-- card.// -->


						<article class="card mb-4">
							<div class="card-body">
								<h4 class="card-title mb-4">Delivery info</h4>
								<form action="">


									<div class="row">
										<div class="form-group col-sm-6">
											<label>Country*</label>
											<select name="" class="form-control">
												<option value="">India</option>
												<option value="">United States</option>
												<option value="">France</option>
												<option value="">Italy</option>
											</select>
										</div>
										<div class="form-group col-sm-6">
											<label>State*</label>
											<input type="text" placeholder="Type here" class="form-control">
										</div>
										<div class="form-group col-sm-8">
											<label>Street*</label>
											<input type="text" placeholder="Type here" class="form-control">
										</div>
										<div class="form-group col-sm-4">
											<label>Building</label>
											<input type="text" placeholder="" class="form-control">
										</div>
										<div class="form-group col-sm-4">
											<label>House</label>
											<input type="text" placeholder="Type here" class="form-control">
										</div>
										<div class="form-group col-sm-4">
											<label>Postal code</label>
											<input type="text" placeholder="" class="form-control">
										</div>
										<div class="form-group col-sm-4">
											<label>Zip</label>
											<input type="text" placeholder="" class="form-control">
										</div>
									</div> <!-- row.// -->
								</form>
							</div> <!-- card-body.// -->
						</article> <!-- card.// -->


						<article class="accordion" id="accordion_pay">
							<div class="card">
								<header class="card-header">
									<img src='{% static "images/misc/payment-paypal.png" %}' class="float-right" height="24">
									<label class="form-check collapsed" data-toggle="collapse"
										data-target="#pay_paynet">
										<input class="form-check-input" name="payment-option" checked type="radio"
											value="option2">
										<h6 class="form-check-label">
											Paypal
										</h6>
									</label>
								</header>
								<div id="pay_paynet" class="collapse show" data-parent="#accordion_pay">
									<div class="card-body">
										<p class="text-center text-muted">Connect your PayPal account and use it to pay
											your bills. You'll be redirected to PayPal to add your billing information.
										</p>
										<p class="text-center">
											<a href="#"><img src='{% static "/images/misc/btn-paypal.png" %}' height="32"></a>
											<br><br>
										</p>
									</div> <!-- card body .// -->
								</div> <!-- collapse .// -->
							</div> <!-- card.// -->
							<div class="card">
								<header class="card-header">
									<img src='{% static "images/misc/payment-card.png" %}' class="float-right" height="24">
									<label class="form-check" data-toggle="collapse" data-target="#pay_payme">
										<input class="form-check-input" name="payment-option" type="radio"
											value="option2">
										<h6 class="form-check-label"> Credit Card </h6>
									</label>
								</header>
								<div id="pay_payme" class="collapse" data-parent="#accordion_pay">
									<div class="card-body">
										<p class="alert alert-success">Some information or instruction</p>
										<form class="form-inline">
											<input type="text" class="form-control mr-2"
												placeholder="xxxx-xxxx-xxxx-xxxx" name="">
											<input type="text" class="form-control mr-2" style="width: 100px"
												placeholder="dd/yy" name="">
											<input type="number" maxlength="3" class="form-control mr-2"
												style="width: 100px" placeholder="cvc" name="">
											<button class="btn btn btn-success">Button</button>
										</form>
									</div> <!-- card body .// -->
								</div> <!-- collapse .// -->
							</div> <!-- card.// -->

						</article>
						<!-- accordion end.// -->

					</main> <!-- col.// -->
					<aside class="col-md-4">
						<div class="card">
							<div class="card-body">
								<dl class="dlist-align">
									<dt>Total price:</dt>
									<dd class="text-right">$69.97</dd>
								</dl>
								<dl class="dlist-align">
									<dt>Tax:</dt>
									<dd class="text-right"> $10.00</dd>
								</dl>
								<dl class="dlist-align">
									<dt>Total:</dt>
									<dd class="text-right text-dark b"><strong>$59.97</strong></dd>
								</dl>
								<hr>
								<p class="text-center mb-3">
									<img src='{% static "images/misc/payments.png" %}' height="26">
								</p>
								<a href="./place-order.html" class="btn btn-primary btn-block"> Place Order </a>

							</div> <!-- card-body.// -->
						</div> <!-- card.// -->
					</aside> <!-- col.// -->
				</div> <!-- row.// -->

				<!-- ============================ COMPONENT 2 END//  ================================= -->




			</div> <!-- container .//  -->
		</section>
		<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/store/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Create Product
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row py-5">
        <div class="col"></div>
        <div class="col-6">
            <form method="POST" enctype="multipart/form-data" class="py-3">
                {% csrf_token %}

                <!-- Render the form -->
                {{ form|crispy }}

                <div class="row justify-content-end p-3"><button type="submit"
                        class="btn btn-outline-primary">Create</button></div>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>

{% endblock content %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
	Product Details
{% endblock title %}

{% block content %}
<section class="section-content padding-y bg">
	<div class="container">

		<!-- ============================ COMPONENT 1 ================================= -->
		<div class="card">
			<div class="row no-gutters">
				<aside class="col-md-6">
					<article class="gallery-wrap">
						<div class="img-big-wrap">
							<a href="{% if not 'default' in p.product_image.url %}
							{{p.product_image.url}}
							{% endif %}">
							<img class='img-fluid img-responsive' src="{{p.product_image.url}}"
									alt="product image"></a>
						</div> <!-- img-big-wrap.// -->

					</article> <!-- gallery-wrap .end// -->
				</aside>
				<main class="col-md-6 border-left">
					<form action="{% url 'cart:add_cart' p.id %}" method="post">{% csrf_token %}
						<article class="content-body">
							<h2 class="title">{{p.product_name}}</h2>
							<div class="mb-3">
								<var class="price h4">$ {{p.price | intcomma}}</var>
							</div>
							<p>{{category_slug}}</p>
							<hr>
							<div class="row">
								<div class="item-option-select">
									<h6>Choose Color</h6>
									<select name="color" class="form-control" >
										<option value="" disabled selected>...</option>
										{% for i in p.variation_set.colors %}
										<option value="{{i.variation_value | lower}}" class="">{{i.variation_value | capfirst}}</option>
										{% endfor %}
									</select>
								</div>
							</div> <!-- row.// -->
							<div class="row">
								<div class="item-option-select">
									<h6>Select Size</h6>
									<select name="size" class="form-control" >
										<option value="" disabled selected>...</option>
										{% for i in p.variation_set.sizes %}
										<option value="{{i.variation_value | lower}}" class="">{{i.variation_value | capfirst}}
										</option>
										{% endfor %}
									</select>
								</div>
							</div>
							<hr>
							{% if p.stock > 0 %}
							{% if is_cart_item  %}
							<div class="row justify-content-around">
								<button class="btn btn-success" disabled>
									Added to cart <i class="fas fa-check    "></i>
								</button>
								<a href="{% url 'cart:cart' %}" class="btn btn-outline-primary">
									View in cart <i class="fas fa-eye px-2"></i>
								</a>
							</div>
							{% else %}
							<button type="submit" class="btn  btn-primary">
								<span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>
							</button>
							{% endif %}
							{% else %}
							<div class="alert alert-danger" role="alert">
								<strong>This product is out of stock!</strong>
							</div>
							{% endif %}
						</article> <!-- product-info-aside .// -->
					</form>
				</main> <!-- col.// -->
			</div> <!-- row.// -->
		</div> <!-- card.// -->
		<!-- ============================ COMPONENT 1 END .// ================================= -->
		<br>
		<div class="row">
			<div class="col-md-9">
				<header class="section-heading">
					<h3>Customer Reviews </h3>
				</header>
				<article class="box mb-3">
					<div class="icontext w-100">
						<img src='{% static "images/avatars/avatar2.jpg" %}' class="img-xs icon rounded-circle"
							alt="avatar image">
						<div class="text">
							<span class="date text-muted float-md-right">24.04.2020 </span>
							<h6 class="mb-1">Mike John </h6>
						</div>
					</div> <!-- icontext.// -->
					<div class="mt-3">
						<p>
							Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip
						</p>
					</div>
				</article>
			</div> <!-- col.// -->
		</div> <!-- row.// -->
	</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/store/product_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Product List
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row py-5">
        <div class="col"></div>
        <div class="col-10">
            <div class="row justify-content-end">
                <div class="col-2">
                    <a href="{% url 'product_create' %}" class="btn-sm btn-outline-primary">
                        <i class="far fa-plus-square"></i> Add Product</a>
                </div>
                <div class="col-2">
                    <a href="{% url 'category:category_add' %}" class="btn-sm btn-outline-primary">
                        <i class="far fa-plus-square"></i> Add Category
                    </a>
            </div>
            <table class="table table-hover table-responsive table-striped table-borderless">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Slug</th>
                        <th scope="col">Description</th>
                        <th scope="col">Price</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Is Available</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        <th scope="row">{{product.id}}</th>
                        <td>{{product.product_name}}</td>
                        <td>{{product.slug}}</td>
                        <td>{{product.description}}</td>
                        <td>{{product.price}}</td>
                        <td>{{product.stock}}</td>
                        <td>{{product.is_available}}</td>
                        <td>
                            <a href='{% url "product_update" product.id %}' class="btn-outline-info btn-sm">
                                View...
                            </a>
                        </td>
                        <td>
                            <a href='{% url "product_delete" product.id %}' class="btn-outline-danger btn-sm">
                                Delete
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col"></div>
    </div>
</div>

{% endblock content %}